# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registrasi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(811, 459)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 190, 71, 16))
        self.label_3.setObjectName("label_3")
        self.imglbl = QtWidgets.QLabel(Dialog)
        self.imglbl.setGeometry(QtCore.QRect(450, 50, 320, 240))
        self.imglbl.setFrameShape(QtWidgets.QFrame.Panel)
        self.imglbl.setText("")
        self.imglbl.setObjectName("imglbl")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(140, 160, 281, 21))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 160, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(50, 120, 47, 14))
        self.label_4.setObjectName("label_4")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(140, 120, 281, 21))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(140, 190, 281, 21))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.Daftar = QtWidgets.QPushButton(Dialog)
        self.Daftar.setGeometry(QtCore.QRect(190, 250, 75, 23))
        self.Daftar.setObjectName("Daftar")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(240, 40, 47, 13))
        self.label.setObjectName("label")
        self.ButtonToAbsen = QtWidgets.QPushButton(Dialog)
        self.ButtonToAbsen.setGeometry(QtCore.QRect(670, 370, 101, 23))
        self.ButtonToAbsen.setObjectName("ButtonToAbsen")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Departement"))
        self.label_2.setText(_translate("Dialog", "Nama "))
        self.label_4.setText(_translate("Dialog", "NIP"))
        self.Daftar.setText(_translate("Dialog", "Daftar"))
        self.label.setText(_translate("Dialog", "Registrasi"))
        self.ButtonToAbsen.setText(_translate("Dialog", "Halaman Absensi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
